/**
 * Postgres-backed integration test harness.
 *
 * `withTestDb(fn)` provisions a fresh, uniquely-named database, applies the
 * migrations in `packages/api/drizzle/` to it, hands `fn` a live
 * `postgres.js` client, and drops the database again in a `finally` — so a
 * thrown assertion still tears down and never leaks a database on the target
 * server.
 *
 * ─── What `fn` is connected as (Task B2) ─────────────────────────────────
 *
 * The client handed to `fn` is the database OWNER — the role in
 * `DATABASE_URL`, which created the schema. Every table is under FORCE ROW
 * LEVEL SECURITY, which binds owners too, so that role only gets to write
 * freely because it is a superuser in every supported setup (CI's `postgres`
 * user; a Homebrew install's `$USER`). Point `DATABASE_URL` at a
 * non-superuser and tests that insert rows without setting `app.town_id`
 * will correctly fail.
 *
 * That is deliberate, not an oversight: an owner connection is what schema
 * tests need. It is also why an owner connection proves NOTHING about
 * tenancy isolation. Task B3's gate connects as `tmm_app` (via SET ROLE, or
 * its own client) precisely because a test run as the owner would pass with
 * RLS switched off entirely.
 *
 * ─── Where the test database lives, and why (Task A2, Step 3) ─────────────
 *
 * Two options were considered:
 *
 *   (a) A `postgres:17` service container in CI; developers tunnel to the
 *       project's dev VM (192.168.1.162) locally, or run Postgres locally.
 *   (b) The dev VM for both CI and local runs — one code path.
 *
 * (b) is not just less convenient than (a), it is impossible: GitHub-hosted
 * runners execute on GitHub's own network and have no route to a private
 * LAN address like 192.168.1.162. There is no tunnel a workflow step can
 * open to reach it — that would require a self-hosted runner, which this
 * repo does not have. So the VM cannot serve CI at all, independent of
 * preference. (a) also sidesteps concurrent test runs contending over one
 * shared database on a machine other people use.
 *
 * So: CI provisions a throwaway `postgres:17` service (see
 * `.github/workflows/ci.yml`) and sets `DATABASE_URL` to point at it. This
 * file only ever reads `DATABASE_URL` — it has no VM-specific or
 * CI-specific branches. Locally, a developer points `DATABASE_URL` at
 * whatever Postgres they like: a local install, or an SSH tunnel to the VM
 * (`ssh -f -N -L 15432:127.0.0.1:5432 ben@192.168.1.162
 * -o ExitOnForwardFailure=yes` and then
 * `DATABASE_URL=postgres://postgres:postgres@localhost:15432/postgres`).
 * The default below matches the CI service's own credentials purely so
 * `pnpm test` works with zero setup inside CI; it is not a claim that the
 * VM is reachable from anywhere by default.
 *
 * ─── Why `postgres.js` and not `pg` ─────────────────────────────────────
 *
 * The project standardizes on both `postgres` (postgres.js) and `pg`
 * depending on use case — `pg` is expected to back the dedicated `LISTEN`
 * connection later. For this harness, `postgres.js` is the simpler choice
 * for two concrete reasons: its tagged-template query API
 * (`` sql`SELECT ...` ``) is exactly what test code should be able to write
 * against the client this harness hands back, and its `sql.file(path)`
 * applies a whole multi-statement `.sql` file (including `DO $$ ... $$`
 * blocks) in one call, which is what applying each migration file needs. Using `pg` here would mean either building a
 * template-tag wrapper by hand or hand-rolling multi-statement file
 * execution — extra code for no benefit, since nothing about database
 * provisioning needs `pg`'s feature set.
 */

import postgres from "postgres";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { randomBytes } from "node:crypto";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
// packages/api/src/test -> repo root
const REPO_ROOT = path.join(__dirname, "..", "..", "..", "..");

const MIGRATIONS_DIR = path.join(REPO_ROOT, "packages", "api", "drizzle");
const JOURNAL_PATH = path.join(MIGRATIONS_DIR, "meta", "_journal.json");

// Matches the CI `postgres:17` service defined in .github/workflows/ci.yml.
// Not a claim that this resolves anywhere outside CI — see the file header.
const DEFAULT_DATABASE_URL = "postgres://postgres:postgres@localhost:5432/postgres";

function generateTestDbName(): string {
  // Lowercase alphanumeric + underscore only, well under Postgres's 63-byte
  // identifier limit, and generated by us (never from external input), so
  // it is safe to interpolate directly into DDL below.
  const suffix = randomBytes(6).toString("hex");
  return `tmm_test_${Date.now().toString(36)}_${suffix}`;
}

/**
 * Turn a failure to create the very first database into an actionable
 * error instead of a bare driver error like `role "postgres" does not
 * exist`. That message is accurate but tells a developer nothing about
 * what to do about it — and a fresh clone going red for an unexplained
 * environment reason is exactly how developers learn to ignore red. The
 * underlying error is preserved via `cause`, never hidden.
 */
function explainConnectionFailure(err: unknown): Error {
  const cause = err instanceof Error ? err : new Error(String(err));
  const explicitlySet = process.env.DATABASE_URL !== undefined;
  const reason = explicitlySet
    ? "DATABASE_URL is set, but the harness could not use it to create a database"
    : "DATABASE_URL is not set and the default connection failed";

  return new Error(
    `db-harness: ${reason}. Set DATABASE_URL to a reachable Postgres, e.g. ` +
      "DATABASE_URL=postgres://$USER@localhost:5432/postgres for a Homebrew " +
      "install. CI uses a postgres:17 service container (see " +
      `.github/workflows/ci.yml). Underlying error: ${cause.message}`,
    { cause },
  );
}

/**
 * Provision an isolated Postgres database, apply the migration corpus to
 * it, run `fn` against a live client, and drop the database afterward —
 * even if `fn` throws.
 */
export async function withTestDb<T>(fn: (sql: postgres.Sql) => Promise<T>): Promise<T> {
  const databaseUrl = process.env.DATABASE_URL ?? DEFAULT_DATABASE_URL;
  const dbName = generateTestDbName();

  // Maintenance connection: whatever database DATABASE_URL points at
  // (typically the server's default "postgres" database). Used only to
  // CREATE/DROP the per-test database — never to run application queries.
  const admin = postgres(databaseUrl, { max: 1, onnotice: () => {} });

  try {
    try {
      // CREATE DATABASE cannot run inside a transaction block; a bare
      // postgres.js query outside `sql.begin()` is not wrapped in one, so
      // this is safe as a single statement. This is also the first thing
      // that actually uses the connection, so any failure here is
      // reinterpreted with setup guidance — see explainConnectionFailure.
      await admin.unsafe(`CREATE DATABASE "${dbName}"`);
    } catch (err) {
      throw explainConnectionFailure(err);
    }

    let sql: postgres.Sql | undefined;
    try {
      // Same connection details as `databaseUrl`, pointed at the new
      // database instead of the maintenance one.
      sql = postgres(databaseUrl, { database: dbName, max: 1, onnotice: () => {} });

      await applyMigrations(sql);

      return await fn(sql);
    } finally {
      await sql?.end();
    }
  } finally {
    // WITH (FORCE) drops connections to the target database first, so a
    // leaked client from `fn` throwing before `sql.end()` above still
    // cannot block teardown. Postgres has supported this since v13.
    //
    // Guarded in its own try/catch: if CREATE DATABASE above never
    // succeeded (e.g. the connection-guidance error just above), this
    // DROP is a harmless no-op — but on the SAME broken connection it can
    // throw the same raw driver error again, and a throw from a `finally`
    // silently replaces whatever was already being thrown from the `try`.
    // That would erase the actionable error this function just went out
    // of its way to produce. A teardown failure is logged, never allowed
    // to mask the real failure.
    try {
      await admin.unsafe(`DROP DATABASE IF EXISTS "${dbName}" WITH (FORCE)`);
    } catch (cleanupErr) {
      console.warn(
        `[db-harness] failed to drop test database "${dbName}" during cleanup:`,
        cleanupErr,
      );
    }
    await admin.end();
  }
}

/**
 * Open a SECOND connection to the database `ownerSql` is attached to, running
 * as the non-owner runtime role `tmm_app` (Task B3).
 *
 * Why this exists: the client `withTestDb` hands back is the owner, and in
 * every supported setup that owner is a superuser — so it bypasses RLS
 * outright. Measured on a database with one town row and no tenant context
 * set: the owner connection sees 1, a `tmm_app` connection sees 0. A tenancy
 * test run on the owner connection would therefore pass with RLS switched off
 * entirely, which is why the isolation gate uses this instead.
 *
 * How the role switch is done, and why it is not a login: the baseline creates
 * `tmm_app` NOLOGIN when no superuser has created it out of band (see
 * `0000_baseline.sql` § 4), so there is no password and no direct login to
 * make. It also does `GRANT tmm_app TO current_user`, which makes the `role`
 * startup parameter below legal. `options=-c role=tmm_app` sets that GUC at
 * connection start, so `current_user` is `tmm_app` from the first statement
 * onward and stays that way across transactions — there is no per-transaction
 * `SET ROLE` for a test to forget. `session_user` remains the owner, which is
 * the one way this differs from production; it does not matter, because
 * Postgres decides RLS bypass on the CURRENT role, not the session one
 * (demonstrated by the measurement above, taken on this exact connection
 * shape).
 *
 * The caller owns the returned client and must `end()` it.
 */
export async function connectAsAppRole(ownerSql: postgres.Sql): Promise<postgres.Sql> {
  const [row] = await ownerSql<{ db: string }[]>`SELECT current_database() AS db`;
  const databaseUrl = process.env.DATABASE_URL ?? DEFAULT_DATABASE_URL;
  return postgres(databaseUrl, {
    database: row!.db,
    // One connection, so "the same pooled connection" is a fact rather than a
    // hope — the transaction-leak assertion in the isolation gate depends on
    // two sequential transactions landing on the same backend, and asserts the
    // backend pid to prove they did.
    max: 1,
    onnotice: () => {},
    connection: { options: "-c role=tmm_app" },
  });
}

async function applyMigrations(sql: postgres.Sql): Promise<void> {
  // Same file list, same order, and the same journal cross-check that
  // scripts/build-db-from-repo.sh uses, so this harness and the Stage 1 gate
  // can never quietly diverge on which migrations exist or what order they
  // apply in. Migration filenames are `NNNN_name.sql`, so lexicographic order
  // is journal order.
  //
  // There is no tolerated-failure list any more. There used to be one, for the
  // two corpus files that could not be applied on plain Postgres; the baseline
  // (Task B2) removed both problems at the source, so any failure here is now
  // a real one and aborts.
  const files = fs
    .readdirSync(MIGRATIONS_DIR)
    .filter((f) => f.endsWith(".sql"))
    .sort();

  // A .sql file the journal does not record will never run in production. If
  // one appears here, applying it would make tests pass against a schema no
  // deploy can reproduce — the exact failure mode this whole task exists to
  // close — so refuse rather than guess which side is right.
  const journal = JSON.parse(fs.readFileSync(JOURNAL_PATH, "utf8")) as {
    entries: { tag: string }[];
  };
  const expected = journal.entries.map((e) => `${e.tag}.sql`);
  if (files.join(",") !== expected.join(",")) {
    throw new Error(
      `db-harness: ${MIGRATIONS_DIR} contains [${files.join(", ")}] but ` +
        `${JOURNAL_PATH} records [${expected.join(", ")}]. Refusing to apply an ` +
        "unregistered or missing migration.",
    );
  }

  for (const file of files) {
    await sql.file(path.join(MIGRATIONS_DIR, file));
  }
}
